# route:
#     receiver: 'slack'

# receivers:
#     - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             text: "{{ .CommonAnnotations.description }}"
#             username: 'Prometheus'
#             channel: '#<channel-name>'
#             api_url: 'https://hooks.slack.com/services/<webhook-id>'

# route:
#     receiver: 'discord'

# receivers:
#     - name: 'discord'
#       slack_configs:
#           - send_resolved: true
#             text: "{{ .CommonAnnotations.description }}{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
#             #username: 'Prometheus'
#             #channel: '#<channel-name>'
#             api_url: 'https://discord.com/api/webhooks/1208084044928253952/nQNlgkVQBWOQfrrznSztbQIP-8_WHGuSU1asmUPWY0rxryXRGgGvcQH9AxYKSmD4yah1'

#curl -H "Content-Type: application/json" -X POST -d '{"content":"Hello, World!"}' https://discord.com/api/webhooks/1207809631863447552/Qss9zA3Ta00jZIIbNB3OdDLpUfJDenhx_k5YoBdjiLESUkSIsmN0XM9mMB4zMBl7z_5Z

# route:
#     receiver: 'discord_webhook'
#     repeat_interval: 1h
#     group_by: ['alertname', 'cluster', 'service']
#     group_wait: 5s
#     group_interval: 5s


# receivers:
#     - name: 'discord_webhook'
#       webhook_configs:
#           - url: 'http://discord.alerts:9094'
          
# Conexión de correo gmail

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'email-notifications'


receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'gregory@lazarillo.app'
    from: 'gregory@lazarillo.app'
    smarthost: smtp.gmail.com:587
    auth_username: '{{ .Env.EMAIL_USER }}'
    auth_password: '{{ .Env.EMAIL_PASSWORD }}'

templates:
- '/etc/alertmanager/template/*.tmpl'



